const tamilScript=document.createElement('script');tamilScript.src='js/tamil.js';document.head.appendChild(tamilScript);
document.addEventListener('DOMContentLoaded',()=>{
 const loader=document.querySelector('.loader'); setTimeout(()=>{loader?.classList.add('hide');document.body.classList.remove('loading')},180);
 const menu=document.querySelector('.menu-btn'),links=document.querySelector('.nav-links');menu?.addEventListener('click',()=>links.classList.toggle('open'));links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
 document.querySelectorAll('[data-count]').forEach(el=>{const end=+el.dataset.count;let n=0;const step=Math.max(1,Math.ceil(end/70));const run=()=>{n=Math.min(end,n+step);el.textContent=n.toLocaleString('en-IN')+'+';if(n<end)requestAnimationFrame(run)};new IntersectionObserver((e,o)=>{if(e[0].isIntersecting){run();o.disconnect()}},{threshold:.6}).observe(el)});
 const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
 const top=document.querySelector('.back-top');addEventListener('scroll',()=>top?.classList.toggle('show',scrollY>500));top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
 const modal=document.querySelector('#joinModal');document.querySelectorAll('[data-join]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();modal?.classList.add('open')}));document.querySelectorAll('.close-modal').forEach(x=>x.addEventListener('click',()=>x.closest('.modal').classList.remove('open')));document.querySelectorAll('.modal').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)x.classList.remove('open')}));
 document.querySelectorAll('.gallery button').forEach(b=>b.addEventListener('click',()=>{const lb=document.querySelector('#lightbox');if(lb){lb.querySelector('img').src=b.querySelector('img').src;lb.classList.add('open')}}));
 document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter-btn.active')?.classList.remove('active');b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('[data-category]').forEach(x=>x.style.display=f==='all'||x.dataset.category===f?'':'none')}));
 document.querySelectorAll('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.checkValidity())return f.reportValidity();alert('நன்றி! இந்த மாதிரிப் படிவம் எதிர்கால Google Apps Script இணைப்பிற்குத் தயாராக உள்ளது.');f.reset()}));
});
